// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDS7uhfCXqZeKW96yoAU6NLXlbllF2pg',
    appId: '1:744451374229:web:c877ba956de7dc2a77af9c',
    messagingSenderId: '744451374229',
    projectId: 'moonchild-4462a',
    authDomain: 'moonchild-4462a.firebaseapp.com',
    storageBucket: 'moonchild-4462a.appspot.com',
    measurementId: 'G-WL9LP9MBV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSgRXpn_TK5fuWU4um8qqGgaAUeTj5dE',
    appId: '1:744451374229:android:736f465f9638ebc077af9c',
    messagingSenderId: '744451374229',
    projectId: 'moonchild-4462a',
    storageBucket: 'moonchild-4462a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDggNBaKb-Ww0roZNC6b9qheYIS1wK9o4Q',
    appId: '1:744451374229:ios:d91b337e9e3753a477af9c',
    messagingSenderId: '744451374229',
    projectId: 'moonchild-4462a',
    storageBucket: 'moonchild-4462a.appspot.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDggNBaKb-Ww0roZNC6b9qheYIS1wK9o4Q',
    appId: '1:744451374229:ios:d91b337e9e3753a477af9c',
    messagingSenderId: '744451374229',
    projectId: 'moonchild-4462a',
    storageBucket: 'moonchild-4462a.appspot.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRDS7uhfCXqZeKW96yoAU6NLXlbllF2pg',
    appId: '1:744451374229:web:37f08590f0a3ba7277af9c',
    messagingSenderId: '744451374229',
    projectId: 'moonchild-4462a',
    authDomain: 'moonchild-4462a.firebaseapp.com',
    storageBucket: 'moonchild-4462a.appspot.com',
    measurementId: 'G-3RFSB986Q0',
  );
}
